'use strict';

var _ = require('lodash');

module.exports = function (bot) {

    var name = "gabbotman92";
    var description = "Frases del twitter gabbotman92. Puede contener chistes machistas, homofobos y linuxeros";
    var frases = [
        "Acabo de compilar un kernel especial para mi procesador y mi PC va un 0'23 % más rápido :D",
        "Linux es la polla.",
        "VIVA ARCH.",
        "Me encanta Debian... EH, ¿WINRAR PUEDE CORROMPER MI SISTEMA?",
        "Fedora mola tanto que tengo un kernel que aún ni han hecho.",
        "MUERRTE A WINDOWS!",
        "PENE.",
        "PUTA.",
        "HABÉIS PERDIDO PUTAS.",
        "Soy @batman",
        "Heeeil macarena.",
        "POLLA.",
        "Usa archlinux PUTA.",
        "Instala ARCH.",
        "Pero tio, ¿usas Ubuntu? Eso es el Linux de los MARICAS.",
        "Me encanta ser trolleado por Ale.",
        "VAMOS A MORIR TODOS.",
        "Necesito cafeeeeee.",
        "Todo se arregla con dinamita",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAH",
        "Sexo.",
        "SEXO. Y ahora que tengo tu atención, MÁS SEXO.",
        "TODAS PUTAS.",
        "@gabboman92 de parte de Ale: CALLA PUTA.",
        "Linux es la polla con cebolla.",
        "Wtf.",
        "No tienes huevos.",
        "Voy a por un café, alguien me presta dinero?",
        "Eso en linux no pasa",
        "Eh, a ligar al parque!",
        "BIBAH GÜINDOWS. Ale, sal de mi twitter.",
        "Los machotes usan arch.",
        "Me encantan los penes. Y no, no estoy siendo trolleado.",
        "Mi distribución linux favorita es ubun.... JAJAJAJAJAJA JAJAJAJAJAJA arch please",
        "¿Copia de seguridad? HEMOS VENIDO A JUGAR.",
        "OH MIERDA HE JODIDO LA BASE DE DATOS.",
        "Vamos a morir todos",
        "sudo rm -rf / --nopreserveroot solucionará tooooooooos los problemas",
        "viva el dota!",
        "soy pro del dota pero solo he jugado 3 veces",
        "dark BATMAN",
        "eh, has oído esto? es rock progresivo britanico-ruso depresivo constructivo",
        "¡Se me ha olvidado la contraseña de mi tarjeta SD!",
        "Los horrores inimaginables son los más fáciles de imaginar",
        "Si los cuchillos están hechos de una cosa y los vasos rotos de otra porque ambos saben a sangre",
        "Si lees este tweet que sepas que HAS PERDIDO.",
        "5 minutos para la gran paja",
        "FAP TIME",
        "Alguna vez te has sentido con ganas de Twittear algo estúpido? Pues lo acabo de hacer. Constantemente.",
        "Cuidado. Se empieza con abrazos y se acaba con... la muerte.",
        "El 69% de los porcentajes acerca de sexo que veais en twitter son falsos, y eso lo sabe un 14% de la gente",
        "▼ ◄ ▲ ► ▼ ◄ ▲ ► ▼ ◄ ▲ ► ▼ ◄ ▲ ► ▼ ◄ ▲ ▼ ◄ ▲ ► ▼ ◄ ▲ ► ▼ ◄▼ ◄ ▲ ► ▼ ◄ ▲ ► ▼Sorry, I've dropped my small bag of illuminati ▲ ► ▼ ◄ ▲ ► ▼ ◄ ▲ ▼",
        "A ELLA LE GUSTA EL FUEGO VALYYYYRIIOOOOO ♪♫♪",
        "odio a john boy, tu odiarás a john boy",
        "quiero una birra pero una buena",
        "dios, que guapo soy",
        "Ninjas católicos nazis americanos del futuro de 1980",
        "Nota mental, no pulsar en un enlace de música si es de alguien de latinoamérica haciendo spam",
        "SOY UN AVIOOON, 11 DE SEPTIEMBRE",
        "ASEREJE, JA DEJE, LA MANO ARRIBA , SINTURA ZOLA, COMO LOS GORILAS, MAYONESAAAA",
        "ASDFASDFASDFJASDFADSFAJDSFAÑDSADSAFDSADSDSAFAFADFADSFADFASDSADSFASDFASFADFSAF(ADSADFSF)+",
        "yo ser ruso nigeriano. Por favor ingresame 666 mil euros en cuenta por bitcoin para pagar cambio de sexo",
        "Cuando sea rico pienso pagar a un piloto para que escriba sobre el cielo de dos hermanas que has perdido. Con tu sangre",
        "SOY TU YO DEL FUTURO. TE HAS DEJADO EL HORNO ENCENDIDO. *chiste de nazis y judios aqui*",
        "hardcore gay porn from the future. or Shazowic labs 6.9",
        "Programar es como montar en bicicleta. Pero la bicicleta está en llamas y tú estás en llamas y todo está en llamas y estás en el infierno.",
        "¿Cómo sabes que alguien es vegano? Fácil, te lo dicen. Igual que los putos linuxeros. Por cierto, viva arch",
        "SOY UN AVIOOOOOOOOON SOY UN AVIOOOOON ONCE DE SEPTIEMBRE",
        "¿Porque la iglesia recomienda la abstención sexual para evitar tener hijos, si así es como nació Jesucristo?",
        "Eh, escucha esto! *grupo de Nigeria del Norte que no conocen ni en su casa*",
        "Los horrores inimaginables son los más fáciles de imaginar",
        "Gracias, ruso de steam que me pasa la banda sonora del hotline miami 2 ",
        "La fruta preferida de los otakus es el mango.",
        "pum pam pum pam pum pam pum pam pum pam pum pam pum pam pum pam pum pam pum pam pum pam pum pam pum pam pum pam",
        "Es como retuitearme a mi mismo pero sin retuitearme a mi mismo. Pero sin el como",
        "El bot que me ha hecho ale es la polla con cebolla",
        "Gente que se queja por esperar 2 años entre temporadas de sherlock: Algunos llevamos esperando desde finales de 2006 el half life 3",
        "¡Se me ha olvidado la contraseña de mi tarjeta SD!",
        "RÁPIDA, EL FBI BUSCA MI PENE. AYÚDAME A ESCONDERLO. EN TU VAGINA",
        "Sabías que bill gates es un robot del futuro? #HECHOSCONFIRMADOS",
        "Sabías que el 69% de estos tweets son el 69% de mis tweets?",
        "ale es puta",
        "que guapo soy",
        "No soy un bot, @gabboman92 es el bot!",
        "Asafdsfjkñl  farafiu farafiu farafiuu(8)",
        "doce doce doce doce doce doce doce doce doce lapiz lapiz lapiz lapiz lapiz lapiz lapiz",
        "I'm not saying that I'm @BillGates . But no one have ever seen us in the same room",
        "I'm not saying that I'm @batman . But no one have ever seen us in the same room",
        "¿Sabéis dónde se puede comprar cloroformo? Es para un amigo",
        "Snapchat es jrasioso",
        "Все знают, что Русский язык является официальным языком Dota 2",
        "❤☮☭ follow for more comunism☭☮❤",
        "Aún no he empezado a ver vikings. Soy demasiado vago :(",
        "I AM (g)ROOT",
        "( ͡ ° ͜ ʖ ͡ ° )",
        "A veces se me va la olla. y eso rima con... CEBOLLA. LOS OGROS SON COMO CEBOLLAS",
        "ALIENS TIO, LOS ALIENS GOBIERNAN ESPAÑA",
        "He perdido en The Game por culpa de @gabboman92 :(",
        "Mi pene es un picaporte ruso",
        "Está el número 17 cansado? Es tis aburría?",
        "Call your girlfriend \"puta\" it means beautiful in spanish",
        "He muerto y no lo sabía. Se aproxima el aniversario de mi muerte :)",
        "Alcantarillas subsuelo núcleo terrestre. Un tweet super profundo :D",
        "¿Cual es tu marca de ropa favorita? NIRVANA",
        "Esto es para los anónimos: si estás stalkeando mi Twitter replanteate tu vida, no soy tan interesante",
        "Divergente... Insurgente... Y por último detergente",
        "Thanks for the gold",
        "Averigua si el botón de rt funciona, prueba con este tweet!",
        "Hola soy kavinsky y me siento sexualmente atraído por los coches",
        "Una de cada 20 personas ha sido víctima de algún crimen. Lo que significa que 19 de cada 20 personas son criminales",
        "Creo recordar que la propiedad intelectual de esa broma pertenecia a... otro que no era yo XD",
        "No os dejéis engañar por el, el autentico soy yo, no @Gabboman92",
        "Cualquier persona: Hola, ¿tienes hora?\n@gabboman92: Soy un usuario de linux y son las 5:45 AM UTC",
        "Tiiio, flamenco fusión, con canciones de Pitingo.",
        "Escucha esto *musica random*. Es pop rock gay hetero.",
        "Shh, no le deis ideas a Ale.",
        "Tengo que verme otra vez la serie evangelion. Fma b apenas hace 6 meses que la vi pero....  JUDRFJHDTVJOLHDDZJOL",
        "El profesor de TIS tiene Twitter?",
        "Quien no conoce la teoría de 6 grados?",
        "Mis pensamientos de esta nueva temporada de juego de tronos: Porno gracioso",
        "Adiós tecno, hola indie: gaboviral",
        "Mi color favorito es el 45 en hexadecimal",
        "Mi contraseña son los últimos 45 dígitos de pi",
        "I HAVE A BONER",
        "Mi cinturón oprime mis pantalones",
        "la la la la la de que será mi gran pizza ",
        "Vamos a jugar a policias y ladrones. DECIDME VUESTRA TARJETA DE CRÉDITO",
        "NO, AUN NO EMPECÉ CON VIKINGS",
        "Archlinux, te echo de menos pero la instalación es demasiado coñazo para hacerla con los exámenes cerca",
        "NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO no me va Internet móvil. Moriré",
        "¿Eres comunista? Entonces qué haces RESPIRANDO MI AIRE LIBERAL Y DEMOCRÁTICO????",
        "He vuelto a perderme en ninguna parte, vuelvo a ser de piedra y todo a mi alrededor es de color",
        "Soy hipster, twiteando letras de grupos disueltos",
        "Escucha este grupo gay hipster, es gaypster.",
        "Nuevos seguidores: 360noscope, unfollows: 69,  tuit inutil (4:20)",
        "Ponerle piña a la pizza debería estar penado con la muerte.",
        "Si haces rt a este tweet te dan Twitter extra, con el que puedes twitear 420 caracteres con hasta 69 líneas",
        "Me quiero leer los libros del the witcher. He oido que son bastante buenos, y no, no he jugado al juego ni pienso hacerlo hasta que lo lea",
        "Hasta arriba de ventolin",
        "Oh no. Los auriculares",
        "A la gente que retuitea cosas en japonés/chino/koreano/starcraftiano, eso lo serás tu, por si es un insulto",
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )( ͡ ° ͜ ʖ ͡ ° )",
        "( ͡ ° ͜ ʖ ͡ ° )OLA WAPA ( ͡ ° ͜ ʖ ͡ ° )",
        "Prueba empírica de que microsoft es ETA y por eso deberías usar linux https://twitter.com/Microsoft/status/527188061311225857"];
    var respuestas = [

        "CALLA E INSTALATE ARCH, PUTA",
        "Porque quiero tu dinero",
        "CALLA PUTA, Y TU TAMBIÉN, @gabboman92",
        "HAS PERDIDO.",
        "Todo se arregla con dinamita",
        "calla e instalate linux!",
        "me dejas un euro para el café?",
        "eso en arch no pasa!",
        "viva linux, puta!",
        "que te folle una piña con pizza!",
        "y por eso los humanos somos seres horribles",
        "PENE",
        "pregunta seria: cerveza o café?",
        "no te has planteado usar una maquina virtual de linux?",
        "Que te metan una piña por el recto",
        "la homosexualidad no es mala. Cásate conmigo y dame pizza",
        "quiero una birra pero una buena",
        "te falta un 69",
        "y eso está para linux?",
        "para eso necesitas ir a 140 km/hora y 1.5 gigavatios",
        "ой, disculpe кабальеро",
        "yo ser ruso nigeriano. Por favor ingresame 666 mil euros en cuenta por bitcoin para pagar cambio de sexo",
        "vas a suspender fruta",
        "YES",
        "has perdido! y @alesevilla92 también!",
        "69",
        "claro que si miarma XD",
        "tio te has pasao XD",
        "usas tostadoras como servidores?",
        "soy como un dragón. Lo más parecido a un amigo es un enemigo que no ha muerto",
        "La verdad es que era una respuesta obvia",
        "me he perdido XD. te odio",
        "chiste de \"tu pene tampoco\" aqui",
        "oye platano, juegas al go en competitivo? XD",
        "EN MI PUEBLO ESO SE LLAMAN CHOCHOS",
        "Te mataré y encima te quedas sin tarta.",
        "puedes usar una teta?",
        "ESO ES MAÑANA",
        "calla que vienes a mi pueblo sin avisar mala persona",
        "nah",
        "I HAD EARGASMS",
        "alejate de támbler XD",
        "ya le di, habia 99 laics y un dislique",
        "Quieres que te llame por whatsapp?",
        "es una rom, enchufo un cable y hago magia negra",
        "estás soñando. La prueba es que el botón de rt aqui no funciona",
        "sigue soñando",
        "illuminati confirmed",
        "eso es porque te tocas por las noches, fruta",
        "your ass belongs to me now.",
        "te imaginas?",
        "tetas?",
        "eso es del dota 2?",
        "has probado con un misil nuclear? Sin gente viva no hay tráfico",
        "DICKS",
        "oh, eras tu. PUTA",
        "buuu",
        "PUTAS? falta @FukenElTuerto",
        "eso requiere demasiado esfuerzo",
        "Thanks for the gold",
        "eso díselo a THEGAME",
        "( ͡ ° ͜ ʖ ͡ ° )",
        "anda enseñame las tetas XD",
        "gayyyyyy",
        "Hitler?",
        "nazis zombis vs arañas ciborg",
        "FAP TIME",
        "prueba la droga y visita el espacio",
        "que es eso?",
        "a eso se le puede instalar linux?",
        "abre redtube",
        "no te has visto kung fury?",
        "usa laxante",
        "Tengo tumblr, se demasiado ya",
        "QUEMALO TODO",
        "respuesta: con tu mano derecha",
        "de onde es pa no aserkarme musho",
        "hay versión porno de eso?",
        "I HAVE A BONER",
        "te odio.",
        "me he perdido. Como tu acabas de perder THE GAME",
        "que te peten",
        "quiero tu droga",
        "deja el porno",
        "Pero lo importante: HAY TETAS?",
        "calla gay",
        "duchate con la tostadora!",
    ];
    var exec = function (msg) {
        var pregunta = msg.command.params[0] || null;
        if (pregunta == null) {
            bot.sendMessage(msg.chat.id, frases[_.random(frases.length - 1)]);
        }
        else {
            bot.sendMessage(msg.chat.id, respuestas[_.random(respuestas.length - 1)] );
        }
    };

    return {
        name: name,
        exec: exec,
        description: description
    }
};
